/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-17 01:35:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.join_005fMember;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_005fuser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1683703012000L));
    _jspx_dependants.put("jar:file:/D:/choronglee/JSPProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/everymal/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("    ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("      <meta charset=\"UTF-8\" />\r\n");
      out.write("      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("      <title>개인회원 회원가입</title>\r\n");
      out.write("      <script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("      <script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("      <script>\r\n");
      out.write("        function kakaopost() {\r\n");
      out.write("          new daum.Postcode({\r\n");
      out.write("            oncomplete: function (data) {\r\n");
      out.write("              document.querySelector(\"#zipcode\").value = data.zonecode;\r\n");
      out.write("              document.querySelector(\"#address1\").value = data.address\r\n");
      out.write("            }\r\n");
      out.write("          }).open();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function maxLengthCheck(object) {\r\n");
      out.write("          if (object.value.length > object.maxLength) {\r\n");
      out.write("            object.value = object.value.slice(0, object.maxLength);\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function submit() {\r\n");
      out.write("          //회원정보 저장\r\n");
      out.write("          data = $(\"#joinForm\").serialize();\r\n");
      out.write("          $.ajax({\r\n");
      out.write("            type: \"post\",\r\n");
      out.write("            async: false,\r\n");
      out.write("            dataType: \"text\",\r\n");
      out.write("            url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/addMember.do\",\r\n");
      out.write("            data: data,\r\n");
      out.write("            success: function (result) {\r\n");
      out.write("              var user_code = result;\r\n");
      out.write("              //동물정보 저장\r\n");
      out.write("              $(\"form[name=joinAnimalForm]\").each(function (index, item) {\r\n");
      out.write("                data = $(\"#joinAnimalForm_\" + index).serialize();\r\n");
      out.write("                data = data + \"&user_code=\" + user_code;\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                  type: \"post\",\r\n");
      out.write("                  async: false,\r\n");
      out.write("                  dataType: \"text\",\r\n");
      out.write("                  url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/animal/addAnimal.do\",\r\n");
      out.write("                  data: data\r\n");
      out.write("                });\r\n");
      out.write("              });\r\n");
      out.write("            }\r\n");
      out.write("          });\r\n");
      out.write("          next();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function next() {\r\n");
      out.write("          alert('회원가입완료.');\r\n");
      out.write("          location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function reset() {\r\n");
      out.write("          $(\"#memberArea\").find(':text').val('');\r\n");
      out.write("          $(\"#memberArea\").find(':password').val('');\r\n");
      out.write("          $(\"#user_tel1\").val('선택').prop(\"selected\", true);\r\n");
      out.write("          $(\"#user_tel2\").val(\"\");\r\n");
      out.write("          $(\"#user_tel3\").val(\"\");\r\n");
      out.write("          $(\"input[type='number']\").val(\"\");\r\n");
      out.write("          $(\"#email\").val(\"\")\r\n");
      out.write("          $(\"textarea\").val(\"\");\r\n");
      out.write("          $('select[name=\"pet_types\"]').val('').prop(\"selected\", true);\r\n");
      out.write("          $('select[name=\"b_type\"]').val('').prop(\"selected\", true);\r\n");
      out.write("          $('input[name=\"pet_sex\"]').prop('checked', false);\r\n");
      out.write("        }\r\n");
      out.write("        function check() {\r\n");
      out.write("          if (a == '') {\r\n");
      out.write("            alert('중복체크를 해주세요');\r\n");
      out.write("            joinForm.user_id.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("          if (a == 'not_usable') {\r\n");
      out.write("            alert('사용할 수 없는 ID입니다. 다시 중복체크를 해주세요');\r\n");
      out.write("            joinForm.user_id.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("          /* 이름 유효성 검사 */\r\n");
      out.write("          if (joinForm.user_name.value.length == 0) {\r\n");
      out.write("            alert(\"이름을 입력해주세요.\");\r\n");
      out.write("            joinForm.user_name.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("          /* 비밀번호 및 비밀번호 확인 유효성 검사 */\r\n");
      out.write("          if (joinForm.user_pwd.value.length == 0) {\r\n");
      out.write("            alert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("            joinForm.user_pwd.focus(); // 포커스를 이동시켜 바로 비밀번호를 입력할 수 있게\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("          var pwdRegExp = /^[a-zA-z0-9]{4,8}$/; //비밀번호 유효성 검사\r\n");
      out.write("          if (!pwdRegExp.test(joinForm.user_pwd.value)) {\r\n");
      out.write("            alert(\"비밀번호는 영문 대소문자와 숫자 4~8자리로 입력해야합니다.\");\r\n");
      out.write("            joinForm.user_pwd.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("          if (joinForm.confirmPassword.value.length == 0) {\r\n");
      out.write("            alert(\"비밀번호 확인을 입력해주세요.\");\r\n");
      out.write("            joinForm.confirmPassword.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("          if (joinForm.user_pwd.value != joinForm.confirmPassword.value) {\r\n");
      out.write("            alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("            joinForm.confirmPassword.select(); //이걸로 하면 focus 이동하면서 입력한게 블록으로 선택됨\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("          /* 전화번호 유효성 검사 */\r\n");
      out.write("          if (joinForm.user_tel1.value == \"\") {\r\n");
      out.write("            alert(\"번호를 선택해주세요.\");\r\n");
      out.write("            joinForm.user_tel1.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("          if (joinForm.user_tel2.value.length == 0) {\r\n");
      out.write("            alert(\"전화번호를 입력해주세요.\");\r\n");
      out.write("            joinForm.user_tel2.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("          if (joinForm.user_tel3.value.length == 0) {\r\n");
      out.write("            alert(\"전화번호를 입력해주세요.\");\r\n");
      out.write("            joinForm.user_tel3.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("          if (isNaN(joinForm.user_tel2.value)) {\r\n");
      out.write("            alert(\"전화번호는 숫자만 입력가능합니다.\");\r\n");
      out.write("            joinForm.user_tel2.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("          if (isNaN(joinForm.user_tel3.value)) {\r\n");
      out.write("            alert(\"전화번호는 숫자만 입력가능합니다.\");\r\n");
      out.write("            joinForm.user_tel3.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("          /* 주소 유효성 검사 */\r\n");
      out.write("          if (joinForm.user_zipcode.value.length == 0) {\r\n");
      out.write("            alert(\"주소를 입력해주세요.\");\r\n");
      out.write("            joinForm.user_zipcode.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("          if (joinForm.user_addr1.value.length == 0) {\r\n");
      out.write("            alert(\"주소를 입력해주세요.\");\r\n");
      out.write("            joinForm.user_addr1.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("          if (joinForm.user_addr2.value.length == 0) {\r\n");
      out.write("            alert(\"주소를 입력해주세요.\");\r\n");
      out.write("            joinForm.user_addr2.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("          /* 이메일 유효성 검사 */\r\n");
      out.write("          if (joinForm.user_email.value.length == 0) {\r\n");
      out.write("            alert(\"이메일을 입력해주세요.\");\r\n");
      out.write("            joinForm.user_email.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          /* 동물 유효성 */\r\n");
      out.write("          try {\r\n");
      out.write("            $(\"form[name=joinAnimalForm]\").each(function (index, item) {\r\n");
      out.write("              if ($(\"#joinAnimalForm_\" + index).find('#pet_name').val() == '') {\r\n");
      out.write("                alert(\"반려동물의 이름을 입력해주세요.\");\r\n");
      out.write("                $(\"#joinAnimalForm_\" + index).find('#pet_name').focus();\r\n");
      out.write("                throw 'finish';\r\n");
      out.write("              }\r\n");
      out.write("              if ($(\"#joinAnimalForm_\" + index).find('#pet_age').val() == '') {\r\n");
      out.write("                alert(\"반려동물의 나이을 입력해주세요.\");\r\n");
      out.write("                $(\"#joinAnimalForm_\" + index).find('#pet_age').focus();\r\n");
      out.write("                throw 'finish';\r\n");
      out.write("              }\r\n");
      out.write("              flag = false;\r\n");
      out.write("              for (i = 0; i < $(\"#joinAnimalForm_\" + index).find('input[name=\"pet_sex\"]').length; i++) {\r\n");
      out.write("                if ($(\"#joinAnimalForm_\" + index).find('input[name=\"pet_sex\"]')[i].checked) {\r\n");
      out.write("                  flag = true;\r\n");
      out.write("                  break; // 라디오박스에서는 1개만 선택될 수 있으므로 사용가능\r\n");
      out.write("                }\r\n");
      out.write("              }\r\n");
      out.write("              if (flag == false) {\r\n");
      out.write("                $(\"#joinAnimalForm_\" + index).find('#pet_sex_f').focus();\r\n");
      out.write("                alert(\"반려동물 성별을 체크해주세요.\");\r\n");
      out.write("                throw 'finish';\r\n");
      out.write("              }\r\n");
      out.write("              if ($(\"#joinAnimalForm_\" + index).find('#pet_types').val() == '') {\r\n");
      out.write("                alert(\"반려동물 종을 선택해주세요.\");\r\n");
      out.write("                $(\"#joinAnimalForm_\" + index).find('#pet_types').focus();\r\n");
      out.write("                throw 'finish';\r\n");
      out.write("              }\r\n");
      out.write("              if ($(\"#joinAnimalForm_\" + index).find('#pet_number').val() == '') {\r\n");
      out.write("                alert(\"반려동물 등록번호를 입력해주세요.\");\r\n");
      out.write("                $(\"#joinAnimalForm_\" + index).find('#pet_number').focus();\r\n");
      out.write("                throw 'finish';\r\n");
      out.write("              }\r\n");
      out.write("              if (isNaN($(\"#joinAnimalForm_\" + index).find('#pet_number').val())) {\r\n");
      out.write("                alert(\"반려동물 등록번호는 숫자만 입력가능합니다.\");\r\n");
      out.write("                $(\"#joinAnimalForm_\" + index).find('#pet_number').select();\r\n");
      out.write("                throw 'finish';\r\n");
      out.write("              }\r\n");
      out.write("              if ($(\"#joinAnimalForm_\" + index).find('#b_type').val() == '') {\r\n");
      out.write("                alert(\"반려동물의 혈액형을 선택해주세요.\");\r\n");
      out.write("                $(\"#joinAnimalForm_\" + index).find('#b_type').focus();\r\n");
      out.write("                throw 'finish';\r\n");
      out.write("              }\r\n");
      out.write("              if ($(\"#joinAnimalForm_\" + index).find('#pet_weight').val() == '') {\r\n");
      out.write("                alert(\"반려동물의 몸무게를 입력해주세요.\");\r\n");
      out.write("                $(\"#joinAnimalForm_\" + index).find('#pet_weight').focus();\r\n");
      out.write("                throw 'finish';\r\n");
      out.write("              }\r\n");
      out.write("              if (isNaN($(\"#joinAnimalForm_\" + index).find('#pet_weight').val())) {\r\n");
      out.write("                alert(\"반려동물 몸무게는 숫자만 입력가능합니다.\");\r\n");
      out.write("                $(\"#joinAnimalForm_\" + index).find('#pet_weight').select();\r\n");
      out.write("                throw 'finish';\r\n");
      out.write("              }\r\n");
      out.write("            });\r\n");
      out.write("          } catch (Exception) {\r\n");
      out.write("            if (Exception !== 'finish') throw Exception;\r\n");
      out.write("            else return false;\r\n");
      out.write("          }\r\n");
      out.write("          submit();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        var a = '';\r\n");
      out.write("        function fn_idCheck() {\r\n");
      out.write("          let _id = $(\"#id\").val();\r\n");
      out.write("          if (_id == \"\") {\r\n");
      out.write("            alert(\"중복체크할 ID를 입력하세요\");\r\n");
      out.write("            return; //함수를 종료한다\r\n");
      out.write("          }\r\n");
      out.write("          $.ajax({\r\n");
      out.write("            type: \"post\",\r\n");
      out.write("            async: true, //비동기로 수행\r\n");
      out.write("            dataType: \"text\",\r\n");
      out.write("            url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/idChk.do\",\r\n");
      out.write("            data: { id: _id }, //서버에 전송할 자료= > 매개변수이름:값 _id(체크할ID)를 id이름으로 서버에 전송\r\n");
      out.write("            success: function (idChkVal, textStatus) { //idChkVal는 서버에서 받은 자료\r\n");
      out.write("              if (idChkVal == 'usable') {\r\n");
      out.write("                a = idChkVal;\r\n");
      out.write("                $(\"#resultMessage\").text(\"사용할 수 있는 ID입니다.\");\r\n");
      out.write("              } else {\r\n");
      out.write("                a = idChkVal;\r\n");
      out.write("                $(\"#resultMessage\").text(\"사용할 수 없는 ID입니다.\");\r\n");
      out.write("              }\r\n");
      out.write("            },\r\n");
      out.write("            error: function () {\r\n");
      out.write("              alert(\"서버와 통신 중 에러 발생\");\r\n");
      out.write("            }\r\n");
      out.write("          });\r\n");
      out.write("        }\r\n");
      out.write("      </script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/join.js\"></script>\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/reset.css\" />\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/common.css\" />\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/join.css\" />\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("      <div id=\"container_sub\">\r\n");
      out.write("        <header id=\"header\">\r\n");
      out.write("          <nav>\r\n");
      out.write("            <ul class=\"topNav\">\r\n");
      out.write("              <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/listArticles.do\">1:1온라인 상담</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/emr_Page/emergency.jsp\">24시간 응급실</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/petTaxiPage\">펫택시</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hosfilter\">병원 찾기</a></li>\r\n");
      out.write("              <li>\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("        <h2 class=\"pagetitlte\">회원가입</h2>\r\n");
      out.write("        <section id=\"sidebar_Area\">\r\n");
      out.write("          <div class=\"sidebars\" id=\"sb_sidebar\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section id=\"memberArea\" class=\"memberJoin memberArea\">\r\n");
      out.write("          <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/addMember.do\" method=\"post\" id=\"joinForm\" name=\"joinForm\">\r\n");
      out.write("            <fieldset>\r\n");
      out.write("              <legend>회원가입 정보 입력 폼</legend>\r\n");
      out.write("              <div id=\"user_form\" class=\"formBox\">\r\n");
      out.write("                <div class=\"formSign\"><strong class=\"require\">필수</strong>는 반드시 입력하여야 하는 항목입니다.</div>\r\n");
      out.write("                <h2>회원정보</h2>\r\n");
      out.write("                <p>\r\n");
      out.write("                  <label for=\"name\">성명<strong class=\"require\">필수</strong></label>\r\n");
      out.write("                  <input type=\"text\" id=\"name\" name=\"user_name\" required placeholder=\"홍길동\">\r\n");
      out.write("                </p>\r\n");
      out.write("                <p>\r\n");
      out.write("                  <label for=\"id\">아이디<strong class=\"require\">필수</strong></label>\r\n");
      out.write("                  <input type=\"text\" id=\"id\" name=\"user_id\" required placeholder=\"everymal\">\r\n");
      out.write("                  <input type=\"button\" id=\"idck\" class=\"greenbox\" value=\"ID중복체크\" onclick=\"fn_idCheck();\"><span\r\n");
      out.write("                    id=\"resultMessage\"></span>\r\n");
      out.write("                </p>\r\n");
      out.write("                <p>\r\n");
      out.write("                  <label for=\"password\">비밀번호<strong class=\"require\">필수</strong></label>\r\n");
      out.write("                  <input type=\"password\" id=\"password\" name=\"user_pwd\" required placeholder=\"영문/숫자 4~8자 이내\">\r\n");
      out.write("                </p>\r\n");
      out.write("                <p>\r\n");
      out.write("                  <label for=\"confirmPassword\">비밀번호 확인<strong class=\"require\">필수</strong></label>\r\n");
      out.write("                  <input type=\"password\" id=\"confirmPassword=\" name=\"confirmPassword\" required\r\n");
      out.write("                    placeholder=\"한번 더 입력해주세요\">\r\n");
      out.write("                </p>\r\n");
      out.write("                <p>\r\n");
      out.write("                  <label for=\"user_tel1\">연락처<strong class=\"require\">필수</strong></label>\r\n");
      out.write("                  <select name=\"user_tel1\" id=\"user_tel1\" required>\r\n");
      out.write("                    <option value=\"\" selected=\"selected\">선택</option>\r\n");
      out.write("                    <option value=\"010\">010</option>\r\n");
      out.write("                    <option value=\"011\">011</option>\r\n");
      out.write("                    <option value=\"016\">016</option>\r\n");
      out.write("                    <option value=\"017\">017</option>\r\n");
      out.write("                    <option value=\"018\">018</option>\r\n");
      out.write("                    <option value=\"019\">019</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                  <input type=\"tel\" id=\"user_tel2\" name=\"user_tel2\" maxlength=\"4\" size=\"10\" required>\r\n");
      out.write("                  <input type=\"tel\" id=\"user_tel3\" name=\"user_tel3\" maxlength=\"4\" size=\"10\" required>\r\n");
      out.write("                </p>\r\n");
      out.write("                <p>\r\n");
      out.write("                  <label for=\"addrbtn\" class=\"labelAddress\">주소<strong class=\"require\">필수</strong></label>\r\n");
      out.write("                  <input type=\"button\" class=\"greenbox\" value=\"우편번호찾기\" id=\"addrbtn\" onclick=\"kakaopost()\">\r\n");
      out.write("                  <input type=\"text\" name=\"user_zipcode\" id=\"zipcode\" size=\"10\" readonly required><br>\r\n");
      out.write("                <div id=\"address\">\r\n");
      out.write("                  <input type=\"text\" name=\"user_addr1\" id=\"address1\" size=\"100\" required>\r\n");
      out.write("                  <input type=\"text\" name=\"user_addr2\" id=\"address2\" size=\"100\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <p>\r\n");
      out.write("                  <label for=\"email\">이메일<strong class=\"require\">필수</strong></label>\r\n");
      out.write("                  <input type=\"email\" id=\"email\" name=\"user_email\" size=\"30\" required\r\n");
      out.write("                    placeholder=\"입력 예) everymal@gmail.com\">\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </fieldset>\r\n");
      out.write("          </form>\r\n");
      out.write("          <div id=\"animalinsert\">\r\n");
      out.write("            <div id=\"animalplus\">+</div>\r\n");
      out.write("            <div id=\"animalminus\">-</div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- 동물정보 -->\r\n");
      out.write("          <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/addAnimal.do\" method=\"post\" id=\"joinAnimalForm_0\" name=\"joinAnimalForm\"\r\n");
      out.write("            class=\"joinAnimalForm\">\r\n");
      out.write("            <fieldset>\r\n");
      out.write("\r\n");
      out.write("              <div id=\"pet_form\">\r\n");
      out.write("                <div class=\"formSign\"><strong class=\"require\">필수</strong>는 반드시 입력하여야 하는 항목입니다.</div>\r\n");
      out.write("                <h2>반려동물 정보</h2>\r\n");
      out.write("                <p class=\"pet_name\">\r\n");
      out.write("                  <label for=\"pet_name\">반려동물 이름<strong class=\"require\">필수</strong></label>\r\n");
      out.write("                  <input type=\"text\" id=\"pet_name\" name=\"pet_name\" required placeholder=\"토리\">\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"pet_age\">\r\n");
      out.write("                  <label for=\"pet_age\">반려동물 나이<strong class=\"require\">필수</strong></label>\r\n");
      out.write("                  <input type=\"number\" id=\"pet_age\" name=\"pet_age\" maxlength=\"3\" oninput=\"maxLengthCheck(this)\">\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"pet_gender\">\r\n");
      out.write("                  <label for=\"pet_gender\">반려동물 성별<strong class=\"require\">필수</strong></label>\r\n");
      out.write("                  ♀<input type=\"radio\" id=\"pet_sex_f\" name=\"pet_sex\" value=\"0\" required>\r\n");
      out.write("                  ♂<input type=\"radio\" id=\"pet_sex_m\" name=\"pet_sex\" value=\"1\">\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"zip\">\r\n");
      out.write("                  <label for=\"pet_types\">반려동물 종류<strong class=\"require\">필수</strong></label>\r\n");
      out.write("                  <select name=\"pet_types\" id=\"pet_types\" required>\r\n");
      out.write("                    <option value=\"\" selected=\"selected\">선택</option>\r\n");
      out.write("                    <option value=\"개\">개</option>\r\n");
      out.write("                    <option value=\"고양이\">고양이</option>\r\n");
      out.write("                    <option value=\"소동물\">소동물</option>\r\n");
      out.write("                    <option value=\"어류\">어류</option>\r\n");
      out.write("                    <option value=\"조류\">조류</option>\r\n");
      out.write("                    <option value=\"파충류\">파충류</option>\r\n");
      out.write("                    <option value=\"기타\">기타</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"pet_number\">\r\n");
      out.write("                  <label for=\"pet_number\">반려동물 등록번호<strong class=\"require\">필수</strong></label>\r\n");
      out.write("                  <input type=\"text\" id=\"pet_number\" name=\"pet_number\" maxlength=\"15\" required>\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"b_type\">\r\n");
      out.write("                  <label for=\"b_type\">반려동물 혈액형<strong class=\"require\">필수</strong></label>\r\n");
      out.write("                  <select name=\"b_type\" id=\"b_type\" required>\r\n");
      out.write("                    <option value=\"\" selected=\"selected\">선택</option>\r\n");
      out.write("                    <optgroup label=\"개\">\r\n");
      out.write("                      <option value=\"DEA1.1\">DEA1.1</option>\r\n");
      out.write("                      <option value=\"DEA1.2\">DEA1.2</option>\r\n");
      out.write("                      <option value=\"DEA1.3\">DEA1.3</option>\r\n");
      out.write("                      <option value=\"DEA3\">DEA3</option>\r\n");
      out.write("                      <option value=\"DEA4\">DEA4</option>\r\n");
      out.write("                      <option value=\"DEA5\">DEA5</option>\r\n");
      out.write("                      <option value=\"DEA7\">DEA7</option>\r\n");
      out.write("                    </optgroup>\r\n");
      out.write("                    <optgroup label=\"고양이\">\r\n");
      out.write("                      <option value=\"A\">A</option>\r\n");
      out.write("                      <option value=\"B\">B</option>\r\n");
      out.write("                      <option value=\"AB\">AB</option>\r\n");
      out.write("                    </optgroup>\r\n");
      out.write("                    <optgroup label=\"기타\">\r\n");
      out.write("                      <option value=\"기타\">기타</option>\r\n");
      out.write("                    </optgroup>\r\n");
      out.write("                  </select>\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"pet_weight\">\r\n");
      out.write("                  <label for=\"pet_weight\">반려동물 몸무게<strong class=\"require\">필수</strong></label>\r\n");
      out.write("                  <input type=\"text\" id=\"pet_weight\" name=\"pet_weight\" maxlength=\"3\">\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"pet_etc\">\r\n");
      out.write("                  <label for=\"pet_etc\">반려동물 특이사항</label>\r\n");
      out.write("                  <textarea name=\"pet_etc\" id=\"pet_etc\" cols=\"50\" rows=\"5\"></textarea>\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </fieldset>\r\n");
      out.write("          </form>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"btnJoinArea\">\r\n");
      out.write("          <button type=\"submit\" class=\"btnOk\" onclick=\"return check()\">회원가입</button>\r\n");
      out.write("          <button type=\"reset\" class=\"btnCancle\" onclick=\"reset()\">초기화</button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- fooooooooooooooooooooooooooooooooooooooooooooooooooooooter -->\r\n");
      out.write("        <footer>\r\n");
      out.write("          <ul class=\"bottomNav\">\r\n");
      out.write("            <li>\r\n");
      out.write("              <a id=\"footerLogo\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/EverymalLogo_w.svg\"\r\n");
      out.write("                  alt=\"로고\" style=\"width: 250px; height: auto\" /></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/listArticles.do\">1:1온라인 상담</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/emr_Page/emergency.jsp\">24시간 응급실</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/petTaxiPage\">펫택시</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hosfilter\">병원 찾기</a></li>\r\n");
      out.write("            <li>\r\n");
      out.write("              ");
      if (_jspx_meth_c_005fchoose_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <div class=\"table\">\r\n");
      out.write("            <address>\r\n");
      out.write("              <p>Everymal</p>\r\n");
      out.write("              <p>서울특별시 종로구 중구 12길 33층 123호</p>\r\n");
      out.write("              <p>공동대표. 김경민, 이초롱, 나은비, 황치연, 김소중</p>\r\n");
      out.write("            </address>\r\n");
      out.write("            <div class=\"custom\">\r\n");
      out.write("              <p>고객문의센터</p>\r\n");
      out.write("              <a href=\"tel:010-111-2222\">T. 1111-2222 (10:00 - 19:00 / 점심시간 12:30 - 13:30)</a>\r\n");
      out.write("              <a href=\"mailto:superman@test.com\">E. everymal@gmail.com</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footBtn\">\r\n");
      out.write("              <a href=\"#\">개인정보 처리방침</a>\r\n");
      out.write("              <a href=\"#\">이용약관</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("      </div>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /join_Member/join_user.jsp(3,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /join_Member/join_user.jsp(3,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/join_Member/join_user.jsp(3,4) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                  ");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /join_Member/join_user.jsp(272,18) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty isLogon}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                      ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                      ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /join_Member/join_user.jsp(274,22) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isHos}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/hosMypageInfo\">병원마이페이지</a>\r\n");
          out.write("                      ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/userMypage\">회원마이페이지</a>\r\n");
          out.write("                      ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login.jsp\">로그인•회원가입</a>\r\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f2_reused = false;
    try {
      _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f2.setParent(null);
      int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
      if (_jspx_eval_c_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_c_005fotherwise_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("              ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      _jspx_th_c_005fchoose_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /join_Member/join_user.jsp(456,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty isLogon}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/logindb/logout\">로그아웃</a>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f2 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f2_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      int _jspx_eval_c_005fotherwise_005f2 = _jspx_th_c_005fotherwise_005f2.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login.jsp\">로그인</a>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
      _jspx_th_c_005fotherwise_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f2_reused);
    }
    return false;
  }
}
